import {
  ISACTIVE_SELECT,
  KYC_STATUS_SELECT,
  LOG_TYPE_SELECT,
  MERCHANT_TEMPORARY_STATUS_SELECT,
  MERCHANT_TRANSACTION_TYPE_SELECT,
  ROLES,
  ROLES_REFERRALS_SELECT,
  TRANSACTION_PLAYER_TYPE_SELECT,
  TRANSACTION_STATUS_SELECT,
  TRANSACTION_TYPE_SELECT,
} from ".";

export const TRANSACTIONS_COLUMN = [
  {
    id: "trasactionId",
    numeric: false,
    disablePadding: false,
    label: "ID",
    // filter: true,
  },
  {
    id: "operationId",
    numeric: false,
    disablePadding: false,
    label: "Ref Id",
    filter: true,
  },
  {
    id: "gameType",
    numeric: false,
    disablePadding: false,
    label: "Game",
    // filter: true,
  },
  {
    id: "siteType",
    numeric: false,
    disablePadding: false,
    label: "Site",
    // filter: true,
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Date",
    filter: true,
    filterType: "date",
    sort: true,
  },
  {
    id: "gameId",
    numeric: false,
    disablePadding: false,
    label: "MID",
    isInfo: true,
    title: "Match ID",
    // filter: true,
    sort: true,
  },
  {
    id: "gameMatchCode",
    numeric: false,
    disablePadding: false,
    label: "RC",
    isInfo: true,
    title: "Round Code",
    // filter: true,
    sort: true,
  },
  {
    id: "type",
    numeric: false,
    disablePadding: false,
    filterType: "select",
    filterTypeData: TRANSACTION_TYPE_SELECT,
    filter: true,
    label: "T Type",
    isInfo: true,
    title: "Transaction Type",
  },
  {
    id: "betAmount",
    numeric: false,
    disablePadding: false,
    label: "Bet Amt",
    isInfo: true,
    title: "Bet Amount",
    // filter: true,
    sort: true,
  },
  {
    id: "amount",
    numeric: false,
    disablePadding: false,
    label: "Trans. Amt",
    isInfo: true,
    title: "Transaction Amount",
    // filter: true,
    sort: true,
  },
  {
    id: "betBall",
    numeric: false,
    disablePadding: false,
    label: "Bet Ball",
    // filterType: "select",
    // filterTypeData: TRANSACTION_TYPE_SELECT,
    // filter: true,
  },
  {
    id: "odds",
    numeric: false,
    disablePadding: false,
    label: "Odds",
    // filter: true,
    sort: true,
  },
  {
    id: "win",
    numeric: false,
    disablePadding: false,
    label: "Win Amt",
  },
  {
    id: "lose",
    numeric: false,
    disablePadding: false,
    label: "Lose Amt",
  },
  {
    id: "commission",
    numeric: false,
    disablePadding: false,
    label: "SF",
    isInfo: true,
    title: "Service Fee",
    // filter: true,
    sort: true,
  },
  {
    id: "playerName",
    numeric: false,
    disablePadding: false,
    label: "Player",
  },
  {
    id: "playerType",
    numeric: false,
    disablePadding: false,
    filterType: "select",
    filterTypeData: TRANSACTION_PLAYER_TYPE_SELECT,
    filter: true,
    label: "P Type",
    isInfo: true,
    title: "Player Type",
  },
  {
    id: "operator",
    numeric: false,
    disablePadding: false,
    label: "Op/Ref",
    isInfo: true,
    title: "Operator / Representative",
  },
  { id: "actions", numeric: false, disablePadding: false, label: "" },
];

export const CASH_IN_OUT_COLUMN  = [
  {
    id: "transactionId",
    numeric: false,
    disablePadding: false,
    label: "Transaction Id",
    filter: true,
  },
  {
    id: "temporaryId",
    numeric: false,
    disablePadding: false,
    label: "TemporaryId",
    filter: true,
  },
  {
    id: "operationId",
    numeric: false,
    disablePadding: false,
    label: "Operation Id",
    filter: true,
  },
  {
    id: "playerName",
    numeric: false,
    disablePadding: false,
    label: "Player Name",
    filter: true,
  },
  {
    id: "type",
    numeric: false,
    disablePadding: false,
    label: "Type",
    filterType: "select",
    filterTypeData: MERCHANT_TRANSACTION_TYPE_SELECT,
    filter: true,
  },
  {
    id: "amount",
    numeric: false,
    disablePadding: false,
    label: "Amount",
    // filter: true,
  },
  {
    id: "temporaryStatus",
    numeric: false,
    disablePadding: false,
    label: "Temporary Status",
    filterType: "select",
    filterTypeData: MERCHANT_TEMPORARY_STATUS_SELECT,
    filter: true,
  },
  {
    id: "providerStatus",
    numeric: false,
    disablePadding: false,
    label: "Provider Status",
    filterType: "select",
    filterTypeData: MERCHANT_TEMPORARY_STATUS_SELECT,
    filter: true,
  },
  {
    id: "operationStatus",
    numeric: false,
    disablePadding: false,
    label: "Operation Status",
    filter: true,
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Date",
    filter: true,
    filterType: "date",
    sort: true,
  },
  { id: "actions", numeric: false, disablePadding: false, label: "" },
];


export const GROSSGAMINGREVENUE_COLUMN = [
  {
    id: "gameName",
    numeric: false,
    disablePadding: false,
    label: "Game Name",
  },
  {
    id: "gameRoundCode",
    numeric: false,
    disablePadding: false,
    filter: true,
    label: "Game Round",
  },
  {
    id: "totalBets",
    numeric: false,
    disablePadding: false,
    label: "Total Bets",
  },
  {
    id: "totalWins",
    numeric: false,
    disablePadding: false,
    label: "Total Wins",
  },
  {
    id: "totalLose",
    numeric: false,
    disablePadding: false,
    label: "Total Lose",
  },
  {
    id: "serviceFee",
    numeric: false,
    disablePadding: false,
    label: "Service Fee",
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Created",
    filter: true,
    filterType: "date",
  },
];

export const REFERRAL_COLUMN = [
  {
    id: "fullName",
    numeric: false,
    disablePadding: false,
    label: "Players",
    filter: true,
  },
  {
    id: "role",
    numeric: false,
    disablePadding: false,
    label: "Role",
    filter: true,
    filterType: "select",
    filterTypeData: ROLES_REFERRALS_SELECT,
  },
  {
    id: "mobile",
    numeric: false,
    disablePadding: false,
    label: "Mobile",
    filter: true,
  },
  {
    id: "commission",
    numeric: false,
    disablePadding: false,
    label: "Commission",
    filter: true,
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Created",
    filter: true,
    filterType: "date",
  },
  {
    id: "updatedAt",
    numeric: false,
    disablePadding: false,
    label: "Updated",
    filter: true,
  },
  { id: "actions", numeric: false, disablePadding: false, label: "" },
];

export const REFERRAL_MASTERAGENT_COLUMN = [
  {
    id: "date",
    numeric: false,
    disablePadding: false,
    label: `Date (MDY)`,
    width: "11%",
  },
  {
    id: "role",
    numeric: false,
    disablePadding: false,
    label: "Role",
    width: "12%",
  },
  {
    id: "firstName",
    numeric: false,
    disablePadding: false,
    label: "First Name",
    width: "11%",
  },
  {
    id: "lastName",
    numeric: false,
    disablePadding: false,
    label: "Last Name",
    width: "11%",
  },
  {
    id: "rep",
    numeric: false,
    disablePadding: false,
    label: "Rep (%)",
    width: "10%",
  },
  {
    id: "operator",
    numeric: false,
    disablePadding: false,
    label: "Ope (%)",
    width: "10%",
  },
  {
    id: "earnings",
    numeric: false,
    disablePadding: false,
    label: "Earnings (PHP)",
    width: "10%",
  },
  {
    id: "status",
    numeric: false,
    disablePadding: false,
    label: "Status",
    width: "10%",
  },
]

export const REFERRAL_COLUMN_DAILY = [
  {
    id: "date",
    numeric: false,
    disablePadding: false,
    label: "Date",
    filter: true,
    filterType: "date",
  },
  {
    id: "unique_game_count",
    numeric: false,
    disablePadding: false,
    label: "Games",
  },
  {
    id: "total_bet_count",
    numeric: false,
    disablePadding: false,
    label: "Bets",
  },
  {
    id: "unique_wonprize_count",
    numeric: false,
    disablePadding: false,
    label: "Wins",
  },
  {
    id: "total_bet_amount",
    numeric: false,
    disablePadding: false,
    label: "Total Bets",
  },
  {
    id: "total_wonprize_amount",
    numeric: false,
    disablePadding: false,
    label: "Total Wins",
  },
  {
    id: "total_deposit_count",
    numeric: false,
    disablePadding: false,
    label: "Deposits",
  },
  {
    id: "total_withdrawal_count",
    numeric: false,
    disablePadding: false,
    label: "Withdrawals",
  },
  {
    id: "total_deposit_amount",
    numeric: false,
    disablePadding: false,
    label: "Total Deposit",
  },
  {
    id: "total_withdrawal_amount",
    numeric: false,
    disablePadding: false,
    label: "Total Withdraw",
  },
];

export const REFERRAL_PLAYER_ACTIVITY_COLUMN = [
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Date",
  },
  {
    id: "game",
    numeric: false,
    disablePadding: false,
    label: "Game",
  },
  {
    id: "type",
    numeric: false,
    disablePadding: false,
    label: "Type",
  },
  {
    id: "betOn",
    numeric: false,
    disablePadding: false,
    label: "Bet On",
  },
  {
    id: "amount",
    numeric: false,
    disablePadding: false,
    label: "Amount",
  },
];

export const REFERRAL_PLAYER_ACTIVITY_BYGAMES_COLUMN = [
  {
    id: "game_id",
    numeric: false,
    disablePadding: false,
    label: "Game ID",
  },
  {
    id: "total_bet_count",
    numeric: false,
    disablePadding: false,
    label: "Bets",
  },
  {
    id: "unique_wonprize_count",
    numeric: false,
    disablePadding: false,
    label: "Wins",
  },
  {
    id: "total_bet_amount",
    numeric: false,
    disablePadding: false,
    label: "Total Bet",
  },
  {
    id: "total_wonprize_amount",
    numeric: false,
    disablePadding: false,
    label: "Total Wins",
  },
  {
    id: "date",
    numeric: false,
    disablePadding: false,
    label: "Date",
  },
];

export const REFERRAL_PLAYER_ACTIVITY_BY_DEP_COLUMN = [
  {
    id: "date",
    numeric: false,
    disablePadding: false,
    label: "Date",
    filter: true,
    filterType: "date",
  },
  {
    id: "total_deposit_amount",
    numeric: false,
    disablePadding: false,
    label: "Deposit Amount",
  },
];

export const REFERRAL_PLAYER_ACTIVITY_BY_WITHDRAW_COLUMN = [
  {
    id: "date",
    numeric: false,
    disablePadding: false,
    label: "Date",
    filter: true,
    filterType: "date",
  },
  {
    id: "total_withdrawal_count",
    numeric: false,
    disablePadding: false,
    label: "Withdraw Amount",
  },
];

export const NOTIFICATION_COLUMN = [
  {
    id: "isRead",
    numeric: false,
    disablePadding: false,
    label: "",
    filter: true,
  },
  {
    id: "message",
    numeric: false,
    disablePadding: false,
    label: "Message",
    filter: true,
  },
  {
    id: "module",
    numeric: false,
    disablePadding: false,
    label: "Module",
    filter: true,
  },
  {
    id: "type",
    numeric: false,
    disablePadding: false,
    label: "Type",
    filter: true,
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Created",
    filter: true,
  },
  {
    id: "updatedAt",
    numeric: false,
    disablePadding: false,
    label: "Updated",
    filter: true,
  },
];

export const LOGS_COLUMN = [
  {
    id: "functionality",
    numeric: false,
    disablePadding: false,
    label: "Functionality",
    filter: true,
  },
  {
    id: "message",
    numeric: false,
    disablePadding: false,
    label: "Message",
    filter: true,
  },
  {
    id: "level",
    numeric: false,
    disablePadding: false,
    label: "Level",
    filter: true,
  },
  {
    id: "associatedId",
    numeric: false,
    disablePadding: false,
    label: "Associated ID",
    filter: true,
  },
  {
    id: "associatedType",
    numeric: false,
    disablePadding: false,
    label: "Associated Type",
    filter: true,
  },
   {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Created Date",
    filter: true,
    filterType: "date",
  },
];

export const GAME_OFFERING_COLUMN = [
  {
    id: "name",
    numeric: false,
    disablePadding: false,
    label: "Game Name",
    filter: true,
  },
  {
    id: "label",
    numeric: false,
    disablePadding: false,
    label: "Game Label",
    filter: true,
  },
  {
    id: "isActive",
    numeric: false,
    disablePadding: false,
    label: "Status",
    filter: true,
  },
   {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Created Date",
    filter: true,
    filterType: "date",
  },
  {
    id: "updatedAt",
    numeric: false,
    disablePadding: false,
    label: "Updated",
    filter: true,
  },
  { id: "actions", numeric: false, disablePadding: false, label: "" },
];

export const USER_IN_GAME_COLUMN = [
  {
    id: "mobile",
    numeric: false,
    disablePadding: false,
    label: "Mobile",
    filter: true,
  },
  {
    id: "name",
    numeric: false,
    disablePadding: false,
    label: "Full Name",
    filter: true,
  },
  { id: "actions", numeric: false, disablePadding: false, label: "" },
];

export const KYC_ATTEMPTS_COLUMN = [
  {
    id: "isInitialize",
    numeric: false,
    disablePadding: false,
    label: "ID Submit",
    filter: false,
  },
  {
    id: "isCheckResult",
    numeric: false,
    disablePadding: false,
    label: "ID/Face Scaning",
    filter: false,
  },
  {
    id: "ekycResult",
    numeric: false,
    disablePadding: false,
    label: "KYC Status",
    filter: false,
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "KYC Date",
    filter: false,
  },
  { id: "actions", numeric: false, disablePadding: false, label: "" },
];


export const USER_MANAGEMENT_COLUMN = [
  // { id: "profilePicture", numeric: false, disablePadding: false, label: "" },
  {
    id: "name",
    numeric: false,
    disablePadding: false,
    label: "Name",
    // filter: true,
  },
  {
    id: "mobile",
    numeric: false,
    disablePadding: false,
    label: "Mobile",
    // filter: true,
  },
  {
    id: "isKYC",
    numeric: false,
    disablePadding: false,
    label: "KYC Status",
    filter: true,
    filterType: "select",
    filterTypeData: KYC_STATUS_SELECT,
    role: [
      ROLES.SUPERADMIN.name, 
      ROLES.ADMINISTRATOR.name, 
      ROLES.OPERATOR.name,
      ROLES.SUPERAGENT.name,
      ROLES.MASTERAGENT.name,
      ROLES.AUDITOR.name,
      ROLES.ACCOUNTING.name,
      ROLES.TREASURY.name
    ],
  },
  {
    id: "role",
    numeric: false,
    disablePadding: false,
    label: "Roles",
    role: [],
    // filter: true,
    // filterType: "select",
    // filterTypeData: ROLES_REFERRALS_SELECT,
  },
  {
    id: "supervisor",
    numeric: false,
    disablePadding: false,
    label: "Supervisor",
    // the role that list here is cannot view this column
    role: [
      ROLES.SUPERVISOR.name,
      ROLES.ADMINISTRATOR.name,
      ROLES.SUPERADMIN.name,
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
      ROLES.AUDITOR.name,
      ROLES.ACCOUNTING.name,
      ROLES.TREASURY.name
    ],
    // filter: true,
  },
  {
    id: "verifier",
    numeric: false,
    disablePadding: false,
    label: "Verifier",
    // the role that list here is cannot view this column
    role: [
      ROLES.VERIFIER.name,
      ROLES.ADMINISTRATOR.name,
      ROLES.SUPERADMIN.name,
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
      ROLES.AUDITOR.name,
      ROLES.ACCOUNTING.name,
      ROLES.TREASURY.name
    ],
    // filter: true,
  },
  {
    id: "status",
    numeric: false,
    disablePadding: false,
    label: "Action Status",
    role: [
      ROLES.ADMINISTRATOR.name, 
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
      ROLES.AUDITOR.name,
    ],
    // filter: true,
  },
  {
    id: "verifierApprovedAt",
    numeric: false,
    disablePadding: false,
    label: "Action Date",
    role: [
      ROLES.VERIFIER.name,
      ROLES.ADMINISTRATOR.name,
      ROLES.SUPERADMIN.name,
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
      ROLES.AUDITOR.name,
      ROLES.ACCOUNTING.name,
      ROLES.TREASURY.name
    ],
  },
  {
    id: "supervisorApprovedAt",
    numeric: false,
    disablePadding: false,
    label: "Action Date",
    role: [
      ROLES.SUPERVISOR.name,
      ROLES.ADMINISTRATOR.name,
      ROLES.SUPERADMIN.name,
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
      ROLES.AUDITOR.name,
      ROLES.ACCOUNTING.name,
      ROLES.TREASURY.name
    ],
  },
  {
    id: "balance",
    numeric: false,
    disablePadding: false,
    label: "Balance",
    role: [ 
      ROLES.SUPERVISOR.name,
      ROLES.ADMINISTRATOR.name,
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
      ROLES.AUDITOR.name,
    ],
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Created",
    filter: true,
    filterType: "date",
  },
  {
    id: "updatedAt",
    numeric: false,
    disablePadding: false,
    label: "Updated",
    // filter: true,
    // filterType: "date",
  },
  { id: "actions", numeric: false, disablePadding: false, label: "", 
    role: [
      ROLES.AUDITOR.name,
  ], },
];

export const USER_SESSIONS_COLUMN = [
  {
    id: "id",
    numeric: false,
    disablePadding: false,
    label: "ID",
    filter: true,
  },
  {
    id: "mode",
    numeric: false,
    disablePadding: false,
    label: "Log In",
    filter: true,
  },
  {
    id: "type",
    numeric: false,
    disablePadding: false,
    label: "Log type",
    filter: true,
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Date",
    filter: true,
    filterType: "date",
  },
];

export const CSR_MONITORING_LIST_COLUMN = [
  {
    id: "fullName",
    numeric: false,
    disablePadding: false,
    label: "Full Name",
    filter: true,
  },
  {
    id: "isActive",
    numeric: false,
    disablePadding: false,
    label: "Is Active",
    filterType: "select",
    filterTypeData: ISACTIVE_SELECT,
    filter: true,
  },
];

export const CSR_MONITORING_LOGS_COLUMN = [
  {
    id: "fullName",
    numeric: false,
    disablePadding: false,
    label: "Full Name",
    filter: true,
  },
  {
    id: "type",
    numeric: false,
    disablePadding: false,
    label: "Log Type",
    filterType: "select",
    filterTypeData: LOG_TYPE_SELECT,
    filter: true,
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Log Date and Time",
    filter: true,
    filterType: "date",
  },
];